"""Initial schema: leads, lead_activities, outbox_events, ai_runs.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-12

Written by hand rather than autogenerated, deliberately. Autogenerate needs a
live database to diff against, and the only one available during development was
SQLite — which would have produced a SQLite-flavoured migration (no JSONB, no
partial indexes) for a PostgreSQL production database.

Verify it without a server:

    uv run alembic upgrade head --sql

That renders the exact DDL offline, which is also the right habit before running
a migration against production.

Four tables and no more. There are no clients, deals or content-production
tables, because nothing needs them yet — speculative schema is the most
expensive kind to remove.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: JSONB on PostgreSQL (binary, indexable), plain JSON elsewhere. Declared
#: inline rather than imported from the models: a migration must keep working
#: even after the models it was generated from have moved on.
JSON_DICT = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

#: Every timestamp in this system is timezone-aware UTC.
TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        # The idempotency guard. The UNIQUE constraint below is what actually
        # enforces it: the service's pre-check is only the fast path, and two
        # concurrent submissions of the same form are settled here.
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        # contact
        sa.Column("first_name", sa.String(length=120), nullable=False),
        sa.Column("last_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=512), nullable=True),
        # qualification answers
        sa.Column("industry", sa.String(length=64), nullable=False),
        sa.Column("monthly_revenue", sa.String(length=64), nullable=False),
        sa.Column("monthly_marketing_budget", sa.String(length=64), nullable=False),
        sa.Column("content_volume", sa.String(length=64), nullable=False),
        sa.Column("primary_goal", sa.String(length=64), nullable=False),
        sa.Column("start_timeline", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        # scoring
        sa.Column("lead_score", sa.Integer(), nullable=True),
        sa.Column("lead_temperature", sa.String(length=16), nullable=True),
        sa.Column("score_version", sa.String(length=16), nullable=True),
        sa.Column("score_breakdown", JSON_DICT, nullable=True),
        # process
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        # attribution (no IP address, on purpose: it adds a GDPR obligation and
        # answers nothing the UTM parameters do not already answer)
        sa.Column("utm_source", sa.String(length=255), nullable=True),
        sa.Column("utm_medium", sa.String(length=255), nullable=True),
        sa.Column("utm_campaign", sa.String(length=255), nullable=True),
        sa.Column("utm_content", sa.String(length=255), nullable=True),
        sa.Column("utm_term", sa.String(length=255), nullable=True),
        sa.Column("referrer", sa.String(length=1024), nullable=True),
        sa.Column("landing_page", sa.String(length=1024), nullable=True),
        # CRM sync state
        sa.Column("hubspot_contact_id", sa.String(length=64), nullable=True),
        sa.Column("hubspot_sync_status", sa.String(length=16), nullable=False),
        sa.Column("hubspot_sync_attempts", sa.Integer(), nullable=False),
        sa.Column("hubspot_synced_at", TS, nullable=True),
        sa.Column("hubspot_sync_error", sa.Text(), nullable=True),
        # timestamps — set by the app through the Clock port, with a server
        # default as a safety net against a hand-written INSERT
        sa.Column("created_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("idempotency_key", name="uq_leads_idempotency_key"),
    )
    # Indexed but NOT unique: someone enquiring again six months later is a new
    # lead, not a constraint violation.
    op.create_index(op.f("ix_leads_email"), "leads", ["email"])
    # The dashboard's default sort.
    op.create_index("ix_leads_created_at_desc", "leads", [sa.text("created_at DESC")])
    # The dashboard's most common filter + sort combination.
    op.create_index(
        "ix_leads_temperature_created",
        "leads",
        ["lead_temperature", sa.text("created_at DESC")],
    )
    op.create_index("ix_leads_status", "leads", ["status"])
    # Partial: we only ever query for leads that are NOT synced, so indexing the
    # synced ones would be dead weight on the hot path.
    op.create_index(
        "ix_leads_sync_status_unsynced",
        "leads",
        ["hubspot_sync_status"],
        postgresql_where=sa.text("hubspot_sync_status <> 'synced'"),
    )
    op.create_index("ix_leads_is_demo", "leads", ["is_demo"])

    op.create_table(
        "lead_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type", sa.String(length=48), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        # Free-form so a new kind of actor ("agent:LeadResearchAgent") needs no
        # migration.
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("activity_metadata", JSON_DICT, nullable=False),
        sa.Column("occurred_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_lead_activities_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_activities")),
    )
    op.create_index(
        "ix_lead_activities_lead_occurred",
        "lead_activities",
        ["lead_id", sa.text("occurred_at DESC")],
    )

    op.create_table(
        # This table IS the queue. Living in the same database as `leads` is the
        # whole point: inserting a row here is atomic with inserting the lead,
        # which no external message broker can offer.
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", JSON_DICT, nullable=False),
        # The HTTP request id that caused this event, so a CRM call made ten
        # seconds later traces back to the web request.
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("occurred_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.Column("claimed_at", TS, nullable=True),
        sa.Column("processed_at", TS, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"])
    # The dispatcher's claim query: "due work, oldest first".
    op.create_index("ix_outbox_due", "outbox_events", ["status", "next_attempt_at"])
    op.create_index("ix_outbox_aggregate", "outbox_events", ["aggregate_type", "aggregate_id"])

    op.create_table(
        # One row per LLM call. Exists so "what is this feature costing?" and
        # "did latency regress when we changed the prompt?" are answerable from
        # data rather than from memory.
        "ai_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.Column("output", JSON_DICT, nullable=False),
        # Deliberately unused today: the hook for a thumbs up/down control,
        # which is what turns a pile of runs into an evaluation set.
        sa.Column("human_rating", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", TS, server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_ai_runs_lead_id_leads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_index(op.f("ix_ai_runs_feature"), "ai_runs", ["feature"])
    op.create_index(
        "ix_ai_runs_feature_created", "ai_runs", ["feature", sa.text("created_at DESC")]
    )


def downgrade() -> None:
    """Drop everything, newest table first so foreign keys unwind cleanly.

    This is reliable only because the declarative base sets a naming convention:
    without one, constraints get database-assigned names and a downgrade cannot
    drop what it cannot name.
    """
    op.drop_table("ai_runs")
    op.drop_table("outbox_events")
    op.drop_table("lead_activities")
    op.drop_table("leads")
